### ISSUE TITLE
A few problems with 'babel-plugin-transform-jsxtreme-markdown'

### ISSUE THREAD

**Issue by d4h0** [mapbox/jsxtreme-markdown#48]
Hi,

I tried to use babel-plugin-transform-jsxtreme-markdown together with gatsby and I ran into a few problems.

**# 1**

Adding the plugin to Babel and running 'gatsby develop' leads to the error:

`error There was an error compiling the html.js component for the development server.`

There was no hint whatsoever what the problem could be (but that is more a problem of Gatsby).

When the Babel plugin is removed everything works.

After running 'gatsby build' (with the plugin) I get the following error:

```
  error Generating JavaScript bundles failed

  Error: ./.cache/production-app.js
  Module build failed: Error: Cannot find module 'strip-indent'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15  )
      at Function.Module._load (internal/modules/cjs/loader.js:520:25)
      at Module.require (internal/modules/cjs/loader.js:650:17)
      at require (/Users/danielhochheimer/Projects/ahrin.de2/node_modules/v8-com  pile-cache/v8-compile-cache.js:159:20)
      at Object.<anonymous> (/Users/danielhochheimer/Projects/ahrin.de2/node_mod  ules/@mapbox/jsxtreme-markdown/lib/to-jsx.js:3:21)
      at Module._compile (/Users/danielhochheimer/Projects/ahrin.de2/node_module  s/v8-compile-cache/v8-compile-cache.js:178:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
      at Module.load (internal/modules/cjs/loader.js:612:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
      at Function.Module._load (internal/modules/cjs/loader.js:543:3)
      at Module.require (internal/modules/cjs/loader.js:650:17)
      at require (/Users/danielhochheimer/Projects/ahrin.de2/node_modules/v8-com  pile-cache/v8-compile-cache.js:159:20)
      at Object.<anonymous> (/Users/danielhochheimer/Projects/ahrin.de2/node_mod  ules/@mapbox/jsxtreme-markdown/index.js:4:10)
      at Module._compile (/Users/danielhochheimer/Projects/ahrin.de2/node_module  s/v8-compile-cache/v8-compile-cache.js:178:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
      at Module.load (internal/modules/cjs/loader.js:612:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
      at Function.Module._load (internal/modules/cjs/loader.js:543:3)
      at Module.require (internal/modules/cjs/loader.js:650:17)
      at require (/Users/danielhochheimer/Projects/ahrin.de2/node_modules/v8-com  pile-cache/v8-compile-cache.js:159:20)
      at Object.<anonymous> (/Users/danielhochheimer/Projects/ahrin.de2/node_mod  ules/@mapbox/babel-plugin-transform-jsxtreme-markdown/index.js:4:26)
      at Module._compile (/Users/danielhochheimer/Projects/ahrin.de2/node_module  s/v8-compile-cache/v8-compile-cache.js:178:30)
```

[This](https://github.com/mapbox/jsxtreme-markdown/blob/master/packages/jsxtreme-markdown/package.json) package.json file has 'strip-indent' in devDependencies.

Could it be that 'strip-indent' is a regular dependency?

The error disappears after installing 'strip-indent' myself.

**# 2**

Importing the fake package 'babel-plugin-transform-jsxtreme-markdown/md' does not work:

`This dependency was not found:

* babel-plugin-transform-jsxtreme-markdown/md in ./src/pages/quiz/test.js

To install it, you can run: npm install --save babel-plugin-transform-jsxtreme-markdown/md`

After specifying my own name in packageName everything works.

**# 3**

I selected '${' and '}' as delimiters to get syntax highlighting in my editor, but I get the following error:

`Syntax Error: Placeholders are not supported inside "md" tagged template literals`

It would be great if we could use '${' and '}' as delimiters. Is there any reason why you decided to use '{{' and '}}' instead of '${' and '}'?

Best regards,
Daniel

**Comment by davidtheclark** [comment]
> Could it be that 'strip-indent' is a regular dependency?

Yipes, yep. Thanks for pointing this out.

> Importing the fake package 'babel-plugin-transform-jsxtreme-markdown/md' does not work:

Where is that `This dependency was not found` error coming from? An unfortunate effect of the fake import is that other tools like ESLint, Flow, etc. won't know about it. Maybe we should consider giving up on the fake import and making it a straight-forward global variable ...

> It would be great if we could use '${' and '}' as delimiters.

I don't think so, because then you would be in conflict with regular JS. I chose a different default to avoid that conflict, which also allows you to use template literals *within* interpolated JS expressions.

**Comment by bolus** [comment]
> Where is that This dependency was not found error coming from?

It seems to happen at run time (when I set the option 'packageName' to 'babel-plugin-transform-jsxtreme-markdown/md' the error goes away).

> I don't think so, because then you would be in conflict with regular JS. I chose a different default to avoid that conflict, which also allows you to use template literals within interpolated JS expressions.

How would it conflict with regular JS? Wouldn't it conflict in the same way as using "}}" somewhere within an interpolated JS expressions would?

Maybe delimiters like '${' and '}$' would be a good compromise? My editor still highlights code within and it should be as easy to parse as the defaults.

When I select these delimiters I still get the 'Placeholders are not supported' error, however.

**Comment by d4h0** [comment]
I think I found another issue:

Setting delimiters to ["{", "}"] leads to the following error:

```
Syntax Error: Unexpected token, expected , (1:15)

> 1 | import React from 'react'
    |                ^
```

**Comment by davidtheclark** [comment]
We can add a note to the readme that you should not try to use delimiters that would clash with JS (`${}`) or JSX (`{}`).
