### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by aiwatko** [mapbox/jsxtreme-markdown#54]
After npm install and imporiting jsxtreme-markdown in my component I get the following issue:
`Module not found: Error: Can't resolve 'fs' in 'node_modules/@mapbox/jsxtreme-markdown/node_modules/babel-core/lib/api'`

Any idea what might have gone wrong?

**Comment by kepta** [comment]
@aiwatko this seems like an issue relating to the environment you code is being executed. Could you please give some details about your setup and how you are consuming `jsxtreme-markdown`?

**Comment by aiwatko** [comment]
thanks for quick feedback!

this is the error detail:
```ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/node_modules/@mapbox/jsxtreme-markdown/node_modules/babel-core/lib/api'
    at factoryCallback (/node_modules/webpack/lib/Compilation.js:276:40)
    at factory (/node_modules/webpack/lib/NormalModuleFactory.js:235:20)
    at resolver (/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /node_modules/async/dist/async.js:3888:9
    at /node_modules/async/dist/async.js:473:16
    at iteratorCallback (/node_modules/async/dist/async.js:1062:13)
    at /node_modules/async/dist/async.js:969:16
    at /node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/node_modules/tapable/lib/Tapable.js:252:11)```

Regarding the setup I'm using NextJS, I wanted to consume jsxtreme-markdown within a NextJS page, there is no other special customised configuration. Let me know if any other details would be useful

**Comment by aiwatko** [comment]
For those who will come after:
Solved with 
```
config.node = {
   fs: "empty"
};
```

to `next.config.js`

**Comment by davidtheclark** [comment]
Thanks @aiwatko. I'm not sure whether anybody has tried importing this module into a browser bundle before. Just an idea: you could try importing `toJsx` directory (like, `@mapbox/jsxtreme-markdown/lib/to-jsx`) to avoid adding Babel to the browser bundle.
